language: rust
sudo: false
dist: trusty
rust: nightly
cache: cargo
matrix:
    include:
    - env: TARGET=i686-unknown-linux-musl
    - env: TARGET=x86_64-unknown-linux-musl
    - env: TARGET=i686-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=i686-apple-darwin
      os: osx
    - env: TARGET=x86_64-apple-darwin
      os: osx
before_script:
- export PATH="$PATH:$HOME/.cargo/bin"
- rustup target add "$TARGET" || true
script:
- cargo build --target "$TARGET" --verbose
- cargo test --target "$TARGET" --verbose
